### ISSUE TITLE
Grad - engleska verzija - overlay za zgradu je na srpskom

### ISSUE THREAD

**Issue by igajic80** [vegaitsourcing/website-gradimo-zajedno#55]
https://gradimozajedno.codeforacause.rs/en/zizuko-en/

Overlay prikazuje PRODATO i na engleskoj verziji

**Comment by s-stankov** [comment]
Pronasao sam kod gde se pravi overlay.

<h5 a><strong><code>object-render.js</code></strong></h5>

```js
container.innerHTML = `
	<div class="item__col item__col--sm">
		<div class="item__overlay">
			<span class="item__overlay-span">Prodato</span>
...
```

Koliko ja vidim imamo 2 opcije:
1. Da se taj string prevede na front-u u neki `translations.js`
2. Da saljemo sa back-a jos jedan property `OverlayString` u kojem ce biti `prodato` u odgovarajucem jeziku

Sta mislite sta je bolje da se uradi?
@igajic80 @petramarkovic @mkovacevic01 @antonelaparovic

**Comment by igajic80** [comment]
@s-stankov Napravicu ja neku translations JS variablu koja ce imati taj prevod

**Comment by igajic80** [comment]
@petramarkovic @s-stankov 

Dodata je nova JS varijabla, translations, koja sadrzi prevod.

```
var translations = {
    "Building.Sold": [{
            "item1": "en-US",
            "item2": "Sold"
        }, {
            "item1": "sr-Latn-RS",
            "item2": "Prodato"
        }
    ]
};
```

renderuje se dinamicki iz BE.
Prevodu se pristupa kroz:   `translations['Building.Sold']`

**Comment by s-stankov** [comment]
Izgleda dobro, mergujem PR :slightly_smiling_face:
